[project]
name = "auto-ticket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "schedule>=1.2.2",
    "selenium>=4.41.0",
    "webdriver-manager>=4.0.2",
]
